# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# SITE SETTINGS
title: The Digital Extended Specimen                        # Title in top navigation bar (navbar) and <head>
description: Promoting integrated extensible biodiversity data infrastructures # Site description in <head>
#description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
author: International Partners for the DES                    # Used for copyright statement in footer
#url: ""
#baseurl: "/petri-dish"                   # Only required if your site is in a directory e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/markdown/#links
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://des-international.github.io" # the base hostname & protocol for your site, e.g. http://example.com

repository: des-international/des-international.github.io

# SOCIAL PROFILES
email: buschbom@posteo.de           # Social icon in footer
#twitter_username: jekyllrb           # Social icon in footer
#twitter_image: /assets/images/twitter_card.png
github_username: des-international            # Social icon in footer

# BUILD SETTINGS
#theme: minima
remote_theme: peterdesmet/petridish@3.0
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec
exclude: [vendor]

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: false                    # Show Twitter feed of social.twitter on homepage
archive_permalink: /blog/               # Permalink of page using the archive.html layout, required when using post tags
github_edit: true                       # Show an "edit this page" link in the footer, can also be name of branch (default: main)
colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
font_serif: true                        # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
logo: /assets/theme/images/petri-dish_1f9eb.png   # Logo in navbar, will be displayed with 30px height

# FRONTMATTER DEFAULTS
#defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default                   # Use default.html layout by default for all files
#  - scope:
#      type: posts
#    values:
#      permalink: "/blog/:year/:slug/"   # Use /blog/yyyy/{filename}/ as permalink for all posts

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:year/:slug/"   # Use /blog/yyyy/{filename}/ as permalink for all posts
      background: "assets/backgrounds/Zhangjiajie-Hunan_cncs_enWikipedia_CC-BY-SAIntl40_the_World_Heritage_Site_Wulingyuan_in_Zhangjiajie_of_Hunan_PR_China.jpg"
      background_alt: "Image credit: https://en.wikipedia.org/wiki/zh:user:cncs_wikipedia (CC-BY-SA4)"
      des-international_version: "0.0.1"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"                 # Only required for Petridish website, implied for sites using a theme
      background: "assets/backgrounds/Zhangjiajie-Hunan_cncs_enWikipedia_CC-BY-SAIntl40_the_World_Heritage_Site_Wulingyuan_in_Zhangjiajie_of_Hunan_PR_China.jpg"
      background_alt: "Image credit: https://en.wikipedia.org/wiki/zh:user:cncs_wikipedia (CC-BY-SA4)"
      des-international_version: "0.0.1"

scholar:
  style: elsevier-harvard
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: references.bib

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  reference_tagname: div
  bibliography_list_tag: ul
  bibliography_template: bib

  query: "@*"  
